
import React from 'react';
import {View,Text,Button,Linking} from 'react-native'
import {Notifications} from 'react-native-notifications'
import { getCurrentTimestamp } from 'react-native/Libraries/Utilities/createPerformanceLogger';

const App= () => {
  const notification=()=>
  
  {
    console.log(date);
    console.log(date1);
   return Notifications.postLocalNotification({
      title: "Local notification",
      body: "This notification was generated by the app!",
      extra: "data",
  
  });
  }
  return (
    <View style={{justifyContent:'center',flexDirection:"column",flex:1}}>
      <Text style={{alignSelf:"center",fontSize:30}}>AmeY k Noftifications</Text>
      <Button  title='Notification' onPress={()=>notification()}>
      </Button>
    </View>
  );
};

export default App;